export enum HealthIndicator {
  ANEMIE = 'ANEMIE',
  DIABETE = 'DIABETE',
  ANTICOAGULANT = 'ANTICOAGULANT',
  POIDS = 'POIDS',
  TAILLE = 'TAILLE',
  PRESSION_ARTERIELLE = 'PRESSION_ARTERIELLE',
  GLYCEMIE = 'GLYCEMIE',
  TEMPERATURE = 'TEMPERATURE'
}
